### ISSUE TITLE
Castbar , Target Name Font Size 

### ISSUE THREAD

**Issue by LVNDSCAPE** [frumpymoons/oUF_Abu#8]
Castbar , Target Font size is showing the value you adjusted but the font looks the same as original value.
Have to re-adjust the slider everytime you login.

**Comment by frumpymoons** [comment]
I pushed an update, can you try it again?

**Comment by LVNDSCAPE** [comment]
![Screenshot_8](https://user-images.githubusercontent.com/23572961/96356968-759dd800-111b-11eb-87cd-b99bda2007f9.png)

can confirm working perfectly after your update.

Thank you.

I don't know anything lua but if you need help testing oUF_Abu , lemme know if I can help in any ways.
